import { z } from "zod";
import {
  StructuredAgentFallbackError,
  StructuredAgentResponseError,
  generateStructuredAgentResponseWithFallback,
} from "../../agent/agent-response-loop.js";
import type { AgentManager } from "../../agent/agent-manager.js";
import type { ProviderSnapshotManager } from "../../agent/provider-snapshot-manager.js";
import {
  resolveStructuredGenerationProviders,
  type ResolveStructuredGenerationProvidersOptions,
  type StructuredGenerationDaemonConfig,
} from "../../agent/structured-generation-providers.js";
import type { WorkspaceGitService } from "../../workspace-git-service.js";
import {
  buildMetadataPrompt,
  type MetadataConfigKey,
} from "../../../utils/build-metadata-prompt.js";

export interface PullRequestText {
  title: string;
  body: string;
}

/**
 * Generates a workspace's commit message and pull-request text from its git diff
 * via the agent LLM. The checkout subsystem is the only consumer; it owns the
 * commit/PR commands and asks this for the wording when the user left it blank.
 */
export interface GitMetadataGenerator {
  generateCommitMessage(cwd: string): Promise<string>;
  generatePullRequestText(cwd: string, baseRef?: string): Promise<PullRequestText>;
}

/**
 * The LLM boundary, injected so the generator's prompt-building and fallback
 * behaviour is unit-testable with a fake. Production wires
 * createAgentStructuredTextGeneration (resolve providers → run structured
 * generation); a failed generation throws StructuredAgent*Error, which the
 * generator catches and turns into the product fallback text.
 */
export interface StructuredTextGeneration {
  generate<T>(request: StructuredTextGenerationRequest<T>): Promise<T>;
}

export interface StructuredTextGenerationRequest<T> {
  cwd: string;
  prompt: string;
  schema: z.ZodType<T>;
  schemaName: string;
  agentTitle: string;
}

type GitMetadataDiffSource = Pick<WorkspaceGitService, "getCheckoutDiff" | "resolveRepoRoot">;
type CheckoutDiffOptions = Parameters<GitMetadataDiffSource["getCheckoutDiff"]>[1];
type CheckoutDiff = Awaited<ReturnType<GitMetadataDiffSource["getCheckoutDiff"]>>;

const COMMIT_MESSAGE_SCHEMA = z.object({
  message: z
    .string()
    .min(1)
    .max(72)
    .describe("Concise git commit message, imperative mood, no trailing period."),
});

const PULL_REQUEST_SCHEMA = z.object({
  title: z.string().min(1).max(72),
  body: z.string().min(1),
});

const COMMIT_MESSAGE_FALLBACK = "Update files";
const PULL_REQUEST_FALLBACK: PullRequestText = {
  title: "Update changes",
  body: "Automated PR generated by Paseo.",
};

const MAX_COMMIT_PATCH_CHARS = 120_000;
const MAX_PULL_REQUEST_PATCH_CHARS = 200_000;
const METADATA_GENERATION_TIMEOUT_MS = 30_000;

interface PromptForDiffInput {
  cwd: string;
  diffOptions: CheckoutDiffOptions;
  maxPatchChars: number;
  contract: string;
  styleConfigKey: MetadataConfigKey;
  styleDefault: string;
  jsonFieldsHint: string;
}

export function createGitMetadataGenerator(deps: {
  workspaceGitService: GitMetadataDiffSource;
  generation: StructuredTextGeneration;
}): GitMetadataGenerator {
  const { workspaceGitService, generation } = deps;

  async function buildPromptForDiff(input: PromptForDiffInput): Promise<string> {
    const diff = await workspaceGitService.getCheckoutDiff(input.cwd, input.diffOptions);
    const fileList = renderFileList(diff.structured);
    const patch = truncatePatch(diff.diff, input.maxPatchChars);
    return buildMetadataPrompt({
      cwd: input.cwd,
      workspaceGitService,
      contract: input.contract,
      styles: [{ configKey: input.styleConfigKey, default: input.styleDefault }],
      after: [
        input.jsonFieldsHint,
        "",
        fileList,
        "",
        patch.length > 0 ? patch : "(No diff available)",
      ].join("\n"),
    });
  }

  return {
    async generateCommitMessage(cwd) {
      const prompt = await buildPromptForDiff({
        cwd,
        diffOptions: { mode: "uncommitted", includeStructured: true },
        maxPatchChars: MAX_COMMIT_PATCH_CHARS,
        contract: "Write a concise git commit message for the changes below.",
        styleConfigKey: "commitMessage",
        styleDefault: "Concise, imperative mood, no trailing period.",
        jsonFieldsHint: "Return JSON only with a single field 'message'.",
      });
      try {
        const result = await generation.generate({
          cwd,
          prompt,
          schema: COMMIT_MESSAGE_SCHEMA,
          schemaName: "CommitMessage",
          agentTitle: "Commit generator",
        });
        return result.message;
      } catch (error) {
        if (isStructuredGenerationFailure(error)) {
          return COMMIT_MESSAGE_FALLBACK;
        }
        throw error;
      }
    },

    async generatePullRequestText(cwd, baseRef) {
      const prompt = await buildPromptForDiff({
        cwd,
        diffOptions: { mode: "base", baseRef, includeStructured: true },
        maxPatchChars: MAX_PULL_REQUEST_PATCH_CHARS,
        contract: "Write a pull request title and body for the changes below.",
        styleConfigKey: "pullRequest",
        styleDefault: "Clear, descriptive title; body explaining what changed and why.",
        jsonFieldsHint: "Return JSON only with fields 'title' and 'body'.",
      });
      try {
        return await generation.generate({
          cwd,
          prompt,
          schema: PULL_REQUEST_SCHEMA,
          schemaName: "PullRequest",
          agentTitle: "PR generator",
        });
      } catch (error) {
        if (isStructuredGenerationFailure(error)) {
          return PULL_REQUEST_FALLBACK;
        }
        throw error;
      }
    },
  };
}

/**
 * Production StructuredTextGeneration: resolve the structured-generation providers
 * for the cwd, then run the agent with a 2-retry fallback as an internal,
 * non-persisted session.
 */
export function createAgentStructuredTextGeneration(deps: {
  agentManager: AgentManager;
  providerSnapshotManager: Pick<ProviderSnapshotManager, "listProviders">;
  readDaemonConfig: () => StructuredGenerationDaemonConfig;
  getFocusedSelection: (
    cwd: string,
  ) => ResolveStructuredGenerationProvidersOptions["currentSelection"];
}): StructuredTextGeneration {
  return {
    async generate({ cwd, prompt, schema, schemaName, agentTitle }) {
      const providers = await resolveStructuredGenerationProviders({
        cwd,
        providerSnapshotManager: deps.providerSnapshotManager,
        daemonConfig: deps.readDaemonConfig(),
        currentSelection: deps.getFocusedSelection(cwd),
      });
      return generateStructuredAgentResponseWithFallback({
        manager: deps.agentManager,
        cwd,
        prompt,
        schema,
        schemaName,
        maxRetries: 2,
        timeoutMs: METADATA_GENERATION_TIMEOUT_MS,
        providers,
        persistSession: false,
        agentConfigOverrides: {
          title: agentTitle,
          internal: true,
        },
      });
    },
  };
}

function renderFileList(structured: CheckoutDiff["structured"]): string {
  if (!structured || structured.length === 0) {
    return "Files changed: (unknown)";
  }
  return [
    "Files changed:",
    ...structured.map((file) => {
      const changeType = diffChangeTypeFor(file);
      const status = file.status && file.status !== "ok" ? ` [${file.status}]` : "";
      return `${changeType}\t${file.path}\t(+${file.additions} -${file.deletions})${status}`;
    }),
  ].join("\n");
}

function truncatePatch(patch: string, maxPatchChars: number): string {
  if (patch.length <= maxPatchChars) {
    return patch;
  }
  return `${patch.slice(0, maxPatchChars)}\n\n... (diff truncated to ${maxPatchChars} chars)\n`;
}

function diffChangeTypeFor(file: { isNew?: boolean; isDeleted?: boolean }): "A" | "D" | "M" {
  if (file.isNew) return "A";
  if (file.isDeleted) return "D";
  return "M";
}

function isStructuredGenerationFailure(error: unknown): boolean {
  return (
    error instanceof StructuredAgentResponseError || error instanceof StructuredAgentFallbackError
  );
}
